# SPDX-FileCopyrightText: 2024 The OrionOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "SDK"
SPDX-PackageSupplier = "The OrionOS Project"
SPDX-PackageDownloadLocation = "https://github.com/OrionOS/android_lineage-sdk"

[[annotations]]
path = [".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 The OrionOS Project"
SPDX-License-Identifier = "Apache-2.0"
